import { defineConfig } from 'vite';

// Deploys to https://drunkonjava.github.io/rvt-rs/viewer/ — so base must
// match the trailing subdirectory of the published path.
export default defineConfig({
  base: './',
  server: {
    // Viewer is strictly client-side. No proxy, no SSR, no API back-end.
    port: 5173,
    strictPort: true,
    // COOP/COEP are needed so we can eventually use SharedArrayBuffer for
    // cross-thread transfers. Even without it today, setting these now
    // keeps the surface honest.
    headers: {
      'Cross-Origin-Opener-Policy': 'same-origin',
      'Cross-Origin-Embedder-Policy': 'require-corp',
    },
  },
  build: {
    target: 'es2022',
    // Keep source maps in the final bundle — this is an auditable,
    // reverse-engineer-friendly project by design.
    sourcemap: true,
    assetsInlineLimit: 0, // never inline .wasm
  },
  worker: {
    format: 'es',
  },
  optimizeDeps: {
    // The rvt package is generated by wasm-pack at build time. Vite's
    // pre-bundler should not try to scan it.
    exclude: ['rvt'],
  },
});
